### ISSUE TITLE
Publish a package

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/deprecated-mmoda-ontology-helper#1]
@volodymyrss could you add an action to publish this to pypi?

This is the detachment of ontology-related code from the dispatcher https://github.com/oda-hub/dispatcher-app/blob/master/cdci_data_analysis/analysis/ontology.py with the additional methods defined [here](https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/e7b059217512adb4d618ace8ab6266eb783f26c3/dispatcher_plugin_nb2workflow/util.py#L4) and [here](https://github.com/oda-hub/nb2workflow/blob/9f1f37cc277f43bee984a5066b6cddfd535ecbdd/nb2workflow/galaxy.py#L19)

When it becomes a package, I will import it in the corresponding modules

**Comment by volodymyrss** [comment]
closing in favor of https://github.com/oda-hub/oda_api/pull/223
